AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  AuthorizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Tracing: Active
      CodeUri: ./cmd/authorize
      Handler: authorize
