AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Formchata

Resources:
  AuthorizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Tracing: Active
      CodeUri: ./services/auth/cmd/authorize
      Handler: authorize
  FormMicroservice:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services/form/template.yaml
      Parameters:
        AuthorizerArn: !GetAtt AuthorizeFunction.Arn
  # ResponseMicroservice:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: ./services/response/template.yaml
  #     Parameters:
  #       AuthorizerArn: !GetAtt AuthorizeFunction.Arn
